vehicle_data_lookup = {
    'vehicle_type': {
        1: 'Pedal cycle',
        2: 'Motorcycle 50cc and under',
        3: 'Motorcycle 125cc and under',
        4: 'Motorcycle over 125cc and up to 500cc',
        5: 'Motorcycle over 500cc',
        8: 'Taxi/Private hire car',
        9: 'Car',
        10: 'Minibus (8 - 16 passenger seats)',
        11: 'Bus or coach (17 or more pass seats)',
        16: 'Ridden horse',
        17: 'Agricultural vehicle',
        18: 'Tram',
        19: 'Van / Goods 3.5 tonnes mgw or under',
        20: 'Goods over 3.5t. and under 7.5t',
        21: 'Goods 7.5 tonnes mgw and over',
        22: 'Mobility scooter',
        23: 'Electric motorcycle',
        90: 'Other vehicle',
        97: 'Motorcycle - unknown cc',
        98: 'Goods vehicle - unknown weight',
        99: 'Unknown vehicle type (self rep only)'
    },

    'towing_and_articulation': {
        0: 'No tow/articulation',
        1: 'Articulated vehicle',
        2: 'Double or multiple trailer',
        3: 'Caravan',
        4: 'Single trailer',
        5: 'Other tow',
        9: 'unknown (self reported)',
        -1: 'Data missing or out of range',
    },

    'vehicle_manoeuvre': {
        1: 'Reversing',
        2: 'Parked',
        3: 'Waiting to go - held up',
        4: 'Slowing or stopping',
        5: 'Moving off',
        6: 'U-turn',
        7: 'Turning left',
        8: 'Waiting to turn left',
        9: 'Turning right',
        10: 'Waiting to turn right',
        11: 'Changing lane to left',
        12: 'Changing lane to right',
        13: 'Overtaking moving vehicle - offside',
        14: 'Overtaking static vehicle - offside',
        15: 'Overtaking - nearside',
        16: 'Going ahead left-hand bend',
        17: 'Going ahead right-hand bend',
        18: 'Going ahead other',
        99: 'unknown (self reported)',
        -1: 'Data missing or out of range',
    },

    'vehicle_direction_from': {
        0: 'Parked',
        1: 'North',
        2: 'North East',
        3: 'East',
        4: 'South East',
        5: 'South East',
        6: 'South West',
        7: 'West',
        8: 'North West',
        9: 'unknown (self reported)',
    },

    'vehicle_direction_to': {
        0: 'Parked',
        1: 'North',
        2: 'North East',
        3: 'East',
        4: 'South East',
        5: 'South East',
        6: 'South West',
        7: 'West',
        8: 'North West',
        9: 'unknown (self reported)',
    },

    'vehicle_location_restricted_lane': {
        0: 'On main cway - not in restricted lane',
        1: 'Tram/Light rail track',
        2: 'Bus lane',
        3: 'Busway (including guided busway)',
        4: 'Cycle lane (on main carriageway)',
        5: 'Cycleway or shared use footway (not part of  main carriageway)',
        6: 'On lay-by or hard shoulder',
        7: 'Entering lay-by or hard shoulder',
        8: 'Leaving lay-by or hard shoulder',
        9: 'Footway (pavement)',
        10: 'Not on carriageway',
        99: 'unknown (self reported)',
        -1: 'Data missing or out of range',
    },

    'junction_location': {0: 'Not at or within 20 metres of junction',
                          1: 'Approaching junction or waiting/parked at junction approach',
                          2: 'Cleared junction or waiting/parked at junction exit',
                          3: 'Leaving roundabout',
                          4: 'Entering roundabout',
                          5: 'Leaving main road',
                          6: 'Entering main road',
                          7: 'Entering from slip road',
                          8: 'Mid Junction - on roundabout or on main road',
                          9: 'unknown (self reported)',
                          -1: 'Data missing or out of range'
                          },

    'skidding_and_overturning': {0: 'None',
                                 1: 'Skidded',
                                 2: 'Skidded and overturned',
                                 3: 'Jackknifed',
                                 4: 'Jackknifed and overturned',
                                 5: 'Overturned',
                                 9: 'unknown (self reported)',
                                 -1: 'Data missing or out of range'
                                 },

    'hit_object_in_carriageway': {0: 'None',
                                  1: 'Previous accident',
                                  2: 'Road works',
                                  4: 'Parked vehicle',
                                  5: 'Bridge (roof)',
                                  6: 'Bridge (side)',
                                  7: 'Bollard or refuge',
                                  8: 'Open door of vehicle',
                                  9: 'Central island of roundabout',
                                  10: 'Kerb',
                                  11: 'Other object',
                                  12: 'Any animal (except ridden horse)',
                                  99: 'unknown (self reported)',
                                  -1: 'Data missing or out of range'
                                  },

    'vehicle_leaving_carriageway': {
        0: 'Did not leave carriageway',
        1: 'Nearside',
        2: 'Nearside and rebounded',
        3: 'Straight ahead at junction',
        4: 'Offside on to central reservation',
        5: 'Offside on to centrl res + rebounded',
        6: 'Offside - crossed central reservation',
        7: 'Offside',
        8: 'Offside and rebounded',
        9: 'unknown (self reported)',
        -1: 'Data missing or out of range'
    },

    'hit_object_off_carriageway': {
        0: 'None',
        1: 'Road sign or traffic signal',
        2: 'Lamp post',
        3: 'Telegraph or electricity pole',
        4: 'Tree',
        5: 'Bus stop or bus shelter',
        6: 'Central crash barrier',
        7: 'Near/Offside crash barrier',
        8: 'Submerged in water',
        9: 'Entered ditch',
        10: 'Other permanent object',
        11: 'Wall or fence',
        99: 'unknown (self reported)',
        -1: 'Data missing or out of range'
    },

    'first_point_of_impact': {
        0: 'Did not impact',
        1: 'Front',
        2: 'Back',
        3: 'Offside',
        4: 'Nearside',
        9: 'unknown (self reported)',
        -1: 'Data missing or out of range'
    },

    'vehicle_left_hand_drive': {
        1: 'No',
        2: 'Yes',
        9: 'Unknown',
        -1: 'Data missing or out of range'
    },

    'journey_purpose_of_driver': {
        1: 'Journey as part of work',
        2: 'Commuting to/from work',
        3: 'Taking pupil to/from school',
        4: 'Pupil riding to/from school',
        5: 'Other',
        6: 'Not known',
        15: 'Other/Not known',
        -1: 'Data missing or out of range'
    },

    'sex_of_driver': {
        1: 'Male',
        2: 'Female',
        3: 'Not known',
        -1: 'Data missing or out of range'
    },

    'age_band_of_driver': {
        1: '0 - 5',
        2: '6 - 10',
        3: '11 - 15',
        4: '16 - 20',
        5: '21 - 25',
        6: '26 - 35',
        7: '36 - 45',
        8: '46 - 55',
        9: '56 - 65',
        10: '66 - 75',
        11: 'Over 75',
        -1: 'Data missing or out of range'
    },

    'propulsion_code': {
        1: 'Petrol',
        2: 'Heavy oil',
        3: 'Electric',
        4: 'Steam',
        5: 'Gas',
        6: 'Petrol/Gas (LPG)',
        7: 'Gas/Bi-fuel',
        8: 'Hybrid electric',
        9: 'Gas Diesel',
        10: 'New fuel technology',
        11: 'Fuel cells',
        12: 'Electric diesel',
        -1: 'Undefined'
    },

}
